## NUMPY

### Numpy vs Lists

**Lists:** 
- Slower speed
- Require more space

**Numpy:** 
- Faster speed
- Space-efficient

For instance, when storing the number 5:
- Python converts it to binary and uses its built-in integer type.
- In NumPy, we can utilize compact storage formats such as int32 or int8, optimizing space usage.

In lists, each element uses Python's built-in integer type, which includes:
1. Object value
2. Reference count
3. Size
4. Object value

In summary, lists in Python consume more memory due to their inherent structure, whereas NumPy arrays offer faster performance and efficient storage tailored to specific data types.

As NumPy uses fewer bytes of memory, the PC can read fewer bytes quickly. When iterating through a NumPy array, we avoid the need to check for the datatype.

NumPy utilizes contiguous memory, unlike lists where data is scattered, which means that with an 8-item array, a list contains pointers to scattered memory locations, whereas NumPy stores data contiguously, enhancing performance benefits such as:
1. SIMD Vector Processing (Single Instruction Multiple Data)
2. Effective Cache Utilization

**How lists differ from NumPy:**
**Similarities:** Both support operations like insertion, deletion, appending, and concatenation.
**Differences:** Lists cannot perform element-wise multiplication directly (e.g., `[1, 3, 5] * [1, 2, 3]` results in an error), while NumPy arrays can (`np.array([1, 3, 5]) * np.array([1, 2, 3])` results in `np.array([1, 6, 15])`).

**Applications of NumPy:**
1. Mathematics (e.g., as a MATLAB replacement)
2. Plotting (e.g., with Matplotlib)
3. Backend operations (e.g., in Pandas, Connect 4, digital photography, image storage in formats like .png)
4. Machine Learning

In [1]:
import numpy as np

In [2]:
#Initializing Array:
a = np.array([1,2,3])
print("ArrayA:", a)

#2D Array
b = np.array([[1.2,2.3,3.3],[4.1,5.2,6.1]])
print("ArrayB:", b)

ArrayA: [1 2 3]
ArrayB: [[1.2 2.3 3.3]
 [4.1 5.2 6.1]]


In [3]:
#Getting the dimension of Numpy Arrays
print("The Dimension of Array A:", a.ndim)
print("The Dimension of Array B:", b.ndim)

The Dimension of Array A: 1
The Dimension of Array B: 2


In [4]:
#Getting the shape of the Array
print("The Shape of Array A:", a.shape)
print("The Shape of Array B:", b.shape)

The Shape of Array A: (3,)
The Shape of Array B: (2, 3)


In [5]:
#Checking the datatype of the array
print("The Type of Array A:", a.dtype)
print("The Type of Array B:", b.dtype)

The Type of Array A: int32
The Type of Array B: float64


In [6]:
#We can specify the data type of the array at the time of initializing
c = np.array([1.2,4.5,5.6], dtype='int16')
print("Array C: ",c)
print("The Type of Array C:", c.dtype)

Array C:  [1 4 5]
The Type of Array C: int16


In [7]:
#Get Size 
print("The size of Array A:", a.itemsize)
print("The size of Array B:", b.itemsize)
print("The size of Array C:", c.itemsize)


# - item size refers to the size in bytes of each element in the array.
# - It indicates the number of bytes used to store a single element of the array's datatype.
# - dtype = int32, itemsize = 4 


The size of Array A: 4
The size of Array B: 8
The size of Array C: 2


In [8]:
#Get Total Size 
print("The size of Array A:", a.size)
print("The size of Array B:", b.size)
print("The size of Array C:", c.size)

#Wheras, size represents the total number of elements in the array.
# it gives the total count of the elements present in the array.
# for example, array B is of shape (2,3) then the size will be 6 because there are total 6 elements in the array

The size of Array A: 3
The size of Array B: 6
The size of Array C: 3


In [9]:
# Total Memory Consumption
print("The Total Memory Array A has occupied: ",a.itemsize*a.size) # a.nbytes
print("The Total Memory Array B has occupied: ",b.nbytes)
print("The Total Memory Array B has occupied: ",c.nbytes)

# Floats are bigger than Integers.

The Total Memory Array A has occupied:  12
The Total Memory Array B has occupied:  48
The Total Memory Array B has occupied:  6


#### Accessing / Changing specific, elements, rows, columns, etc

In [10]:
# Accessing / Changing specific, elements, rows, columns, etc

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

print("The shape of Array A is: ",a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
The shape of Array A is:  (2, 7)


In [11]:
#Getting a specific Element. [row,column]
print(a[1,5]) 
print(a[1,-2]) # can also use the negative notation

13
13


In [12]:
#Getting a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#Getting a specific column 
a[:,2]

array([ 3, 10])

In [14]:
#Getting a little more fancy [startindex: endindex: stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [15]:
#Change 13
a[1][5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,3] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  1  5  6  7]
 [ 8  9  5  2 12 20 14]]


In [16]:
#3D Example
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
#Getting specific element (work outside in)
d[0,1,1]

4

In [18]:
#Replacing 
d[:,1,:] = [2,3]
print(d)

d[:,1,:] = [[2,3],[4,2]]
print(d)

[[[1 2]
  [2 3]]

 [[5 6]
  [2 3]]]
[[[1 2]
  [2 3]]

 [[5 6]
  [4 2]]]


#### Initializing Different Types of Arrays

In [19]:
#All Zeros
print("1D Array: \n",np.zeros(5),"\n") # 1D Array of shape 5 
print("2D Array: \n",np.zeros((2,3)),"\n") # 2D Array of shape (2,3) 2 rows 3 columns
print("3D Array: \n",np.zeros((2,3,3)),"\n") #3D Array 
print("4D Array: \n",np.zeros((2,3,3,2)),"\n") #4D Array 

1D Array: 
 [0. 0. 0. 0. 0.] 

2D Array: 
 [[0. 0. 0.]
 [0. 0. 0.]] 

3D Array: 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] 

4D Array: 
 [[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]] 



In [20]:
# All 1s Matrix
print("All 1's 1D Array:\n",np.ones(4),"\n")
print("All 1's 2D Array:\n",np.ones((2,3)),"\n")
print("All 1's 3D Array:\n",np.ones((2,3,3)),"\n")

All 1's 1D Array:
 [1. 1. 1. 1.] 

All 1's 2D Array:
 [[1. 1. 1.]
 [1. 1. 1.]] 

All 1's 3D Array:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 



In [21]:
# Can also specify datatype
np.ones((2,3),dtype='int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [22]:
#Any other number initialization
np.full((2,2),99,dtype='float32')
#Shape of the array and the value to be filled in the array of float32

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [23]:
#Any other number(full_like)
#Reusing array A
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
#Initialzing a matrix of random numbers from 0 to 1
print(np.random.rand(4,3),"\n\n")

print(np.random.random_sample(a.shape))

[[0.79789889 0.44391008 0.26966813]
 [0.15596031 0.11611831 0.62492011]
 [0.85821815 0.73842372 0.14403603]
 [0.80289411 0.57932979 0.27886909]] 


[[0.64712958 0.00513959 0.13393594 0.83942459 0.17376738 0.61287366
  0.69281496]
 [0.41749916 0.9434299  0.65811328 0.67242875 0.32882282 0.05362874
  0.4026647 ]]


In [26]:
#Random integer values
np.random.randint(2,7,size=(2,3))
#start integer, end integer and the size of the array
# start integer is assumed to be 0 if not provided
# and the end integer is exclusive! it means the range will be 2 to 6

array([[3, 5, 4],
       [4, 3, 6]])

In [27]:
#Identity Matrix
np.identity(5) #Identity Matrix is a square matrix by nature, it needs only 1 parameter.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#Repeating an Array
arr = np.array([[1,2,3]])
rep1 = np.repeat(arr,3,axis=0)
print(rep1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
z[1][1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [32]:
output
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying Arrays

In [33]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [34]:
#Direct Copy of A
b = a
print(b)

[1 2 3]


In [35]:
b[0] = 100
print(b)
print(a)

#When we did b = a, we stated that b points to the same thing as a does,
# so when we changed the element in array b, the change was applied to a too

[100   2   3]
[100   2   3]


In [36]:
# To prevent this
b = a.copy()
b[2] = 100
print(a)
print(b)

[100   2   3]
[100   2 100]


#### Mathematics

In [37]:
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[100   2   3]
[102   4   5]
[98  0  1]
[200   4   6]
[50.   1.   1.5]


In [38]:
a+=2
print(a)

[102   4   5]


In [39]:
b = np.array([1,0,1,0])
a = np.array([1,2,3,4])
a+b

array([2, 2, 4, 4])

In [40]:
a**2

array([ 1,  4,  9, 16])

In [41]:
#taking sin,cos,tan of all values
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

#### Linear Algebra

In [42]:
a = np.ones((2,3))
print("Array A\n",a)

b = np.full((3,2),2)
print("\nArray B\n",b)

# to Multiply two matrices the columns of the first should be equal to the rows of the second matrix.
# 2 x [3 * 3] x 2
# the resultant matrix will be of 2x2

Array A
 [[1. 1. 1.]
 [1. 1. 1.]]

Array B
 [[2 2]
 [2 2]
 [2 2]]


In [43]:
# We cannot do a*b as they are of two different shapes
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [44]:
#Find the determinant
c = np.identity(3)
print(c)
# We know that the determinant of an identity matrix is 1. Lets check
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### Basic Stats

In [45]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(stats)

1

In [47]:
np.max(stats)

6

In [48]:
np.min(stats,axis=0)

array([1, 2, 3])

In [49]:
np.min(stats,axis=1)

array([1, 4])

In [50]:
np.sum(stats)

21

In [52]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [53]:
np.sum(stats,axis=1)

array([ 6, 15])

#### Reorganizing Arrays

In [57]:
before_array = np.array([[1,2,3,4],[5,6,7,8]])
before_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
before_array.shape

(2, 4)

In [60]:
after_array = before_array.reshape((8,1))
after_array

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [62]:
after_array = before_array.reshape((4,2))
after_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
#Vertically stacking vectors/ matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [67]:
#stacking v1 on v2
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [72]:
#Horizontal Stacking
h1 = np.zeros((2,4))
h2 = np.ones((2,2))
print(h1)
print(h2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [77]:
np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

#### Misc

Loading Data from a file (without pandas)

In [79]:
file_data = np.genfromtxt('data.txt',delimiter=',')
file_data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [83]:
file_data = file_data.astype('int32')
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Boolean Masking & Advance Indexing

In [84]:
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [85]:
file_data[file_data>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [86]:
### We can index in a list in numpy
x = np.array([1,2,3,4,5,6,7,8,9])
x[[1,2,8]] # Passing index as a list

array([2, 3, 9])

In [87]:
np.any(file_data>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [88]:
np.all(file_data >50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [89]:
np.all(file_data >50, axis=1)

array([False, False, False])

In [93]:
(~(file_data >50) & (file_data < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])